name: Cherry-pick

on: [push]

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v1

    - uses: mvktsk/github-action-cherry-pick/cherry-pick/@master
      with:
        pullNumber: 123
        pullUrl: https://github.com/mvktsk/vc-platform/pull/1
        gitUserName: mvktsk        